# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/Evie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/Evie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Evie/CMakeFiles /home/gabriel/Evie/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/Evie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Evie

# Build rule for target.
Evie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Evie
.PHONY : Evie

# fast build rule for target.
Evie/fast:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/build
.PHONY : Evie/fast

Cpp/Architecture/ARM/ARM.o: Cpp/Architecture/ARM/ARM.cpp.o

.PHONY : Cpp/Architecture/ARM/ARM.o

# target to build an object file
Cpp/Architecture/ARM/ARM.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Architecture/ARM/ARM.cpp.o
.PHONY : Cpp/Architecture/ARM/ARM.cpp.o

Cpp/Architecture/ARM/ARM.i: Cpp/Architecture/ARM/ARM.cpp.i

.PHONY : Cpp/Architecture/ARM/ARM.i

# target to preprocess a source file
Cpp/Architecture/ARM/ARM.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Architecture/ARM/ARM.cpp.i
.PHONY : Cpp/Architecture/ARM/ARM.cpp.i

Cpp/Architecture/ARM/ARM.s: Cpp/Architecture/ARM/ARM.cpp.s

.PHONY : Cpp/Architecture/ARM/ARM.s

# target to generate assembly for a file
Cpp/Architecture/ARM/ARM.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Architecture/ARM/ARM.cpp.s
.PHONY : Cpp/Architecture/ARM/ARM.cpp.s

Cpp/Architecture/x86/x86.o: Cpp/Architecture/x86/x86.cpp.o

.PHONY : Cpp/Architecture/x86/x86.o

# target to build an object file
Cpp/Architecture/x86/x86.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Architecture/x86/x86.cpp.o
.PHONY : Cpp/Architecture/x86/x86.cpp.o

Cpp/Architecture/x86/x86.i: Cpp/Architecture/x86/x86.cpp.i

.PHONY : Cpp/Architecture/x86/x86.i

# target to preprocess a source file
Cpp/Architecture/x86/x86.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Architecture/x86/x86.cpp.i
.PHONY : Cpp/Architecture/x86/x86.cpp.i

Cpp/Architecture/x86/x86.s: Cpp/Architecture/x86/x86.cpp.s

.PHONY : Cpp/Architecture/x86/x86.s

# target to generate assembly for a file
Cpp/Architecture/x86/x86.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Architecture/x86/x86.cpp.s
.PHONY : Cpp/Architecture/x86/x86.cpp.s

Cpp/Back/Back.o: Cpp/Back/Back.cpp.o

.PHONY : Cpp/Back/Back.o

# target to build an object file
Cpp/Back/Back.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Back.cpp.o
.PHONY : Cpp/Back/Back.cpp.o

Cpp/Back/Back.i: Cpp/Back/Back.cpp.i

.PHONY : Cpp/Back/Back.i

# target to preprocess a source file
Cpp/Back/Back.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Back.cpp.i
.PHONY : Cpp/Back/Back.cpp.i

Cpp/Back/Back.s: Cpp/Back/Back.cpp.s

.PHONY : Cpp/Back/Back.s

# target to generate assembly for a file
Cpp/Back/Back.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Back.cpp.s
.PHONY : Cpp/Back/Back.cpp.s

Cpp/Back/Definer.o: Cpp/Back/Definer.cpp.o

.PHONY : Cpp/Back/Definer.o

# target to build an object file
Cpp/Back/Definer.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Definer.cpp.o
.PHONY : Cpp/Back/Definer.cpp.o

Cpp/Back/Definer.i: Cpp/Back/Definer.cpp.i

.PHONY : Cpp/Back/Definer.i

# target to preprocess a source file
Cpp/Back/Definer.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Definer.cpp.i
.PHONY : Cpp/Back/Definer.cpp.i

Cpp/Back/Definer.s: Cpp/Back/Definer.cpp.s

.PHONY : Cpp/Back/Definer.s

# target to generate assembly for a file
Cpp/Back/Definer.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Definer.cpp.s
.PHONY : Cpp/Back/Definer.cpp.s

Cpp/Back/Generator.o: Cpp/Back/Generator.cpp.o

.PHONY : Cpp/Back/Generator.o

# target to build an object file
Cpp/Back/Generator.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Generator.cpp.o
.PHONY : Cpp/Back/Generator.cpp.o

Cpp/Back/Generator.i: Cpp/Back/Generator.cpp.i

.PHONY : Cpp/Back/Generator.i

# target to preprocess a source file
Cpp/Back/Generator.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Generator.cpp.i
.PHONY : Cpp/Back/Generator.cpp.i

Cpp/Back/Generator.s: Cpp/Back/Generator.cpp.s

.PHONY : Cpp/Back/Generator.s

# target to generate assembly for a file
Cpp/Back/Generator.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Generator.cpp.s
.PHONY : Cpp/Back/Generator.cpp.s

Cpp/Back/Token.o: Cpp/Back/Token.cpp.o

.PHONY : Cpp/Back/Token.o

# target to build an object file
Cpp/Back/Token.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Token.cpp.o
.PHONY : Cpp/Back/Token.cpp.o

Cpp/Back/Token.i: Cpp/Back/Token.cpp.i

.PHONY : Cpp/Back/Token.i

# target to preprocess a source file
Cpp/Back/Token.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Token.cpp.i
.PHONY : Cpp/Back/Token.cpp.i

Cpp/Back/Token.s: Cpp/Back/Token.cpp.s

.PHONY : Cpp/Back/Token.s

# target to generate assembly for a file
Cpp/Back/Token.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Back/Token.cpp.s
.PHONY : Cpp/Back/Token.cpp.s

Cpp/Emulator/Emulator.o: Cpp/Emulator/Emulator.cpp.o

.PHONY : Cpp/Emulator/Emulator.o

# target to build an object file
Cpp/Emulator/Emulator.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Emulator/Emulator.cpp.o
.PHONY : Cpp/Emulator/Emulator.cpp.o

Cpp/Emulator/Emulator.i: Cpp/Emulator/Emulator.cpp.i

.PHONY : Cpp/Emulator/Emulator.i

# target to preprocess a source file
Cpp/Emulator/Emulator.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Emulator/Emulator.cpp.i
.PHONY : Cpp/Emulator/Emulator.cpp.i

Cpp/Emulator/Emulator.s: Cpp/Emulator/Emulator.cpp.s

.PHONY : Cpp/Emulator/Emulator.s

# target to generate assembly for a file
Cpp/Emulator/Emulator.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Emulator/Emulator.cpp.s
.PHONY : Cpp/Emulator/Emulator.cpp.s

Cpp/Interpreter/Interpreter.o: Cpp/Interpreter/Interpreter.cpp.o

.PHONY : Cpp/Interpreter/Interpreter.o

# target to build an object file
Cpp/Interpreter/Interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Interpreter/Interpreter.cpp.o
.PHONY : Cpp/Interpreter/Interpreter.cpp.o

Cpp/Interpreter/Interpreter.i: Cpp/Interpreter/Interpreter.cpp.i

.PHONY : Cpp/Interpreter/Interpreter.i

# target to preprocess a source file
Cpp/Interpreter/Interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Interpreter/Interpreter.cpp.i
.PHONY : Cpp/Interpreter/Interpreter.cpp.i

Cpp/Interpreter/Interpreter.s: Cpp/Interpreter/Interpreter.cpp.s

.PHONY : Cpp/Interpreter/Interpreter.s

# target to generate assembly for a file
Cpp/Interpreter/Interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Interpreter/Interpreter.cpp.s
.PHONY : Cpp/Interpreter/Interpreter.cpp.s

Cpp/Interpreter/Modder.o: Cpp/Interpreter/Modder.cpp.o

.PHONY : Cpp/Interpreter/Modder.o

# target to build an object file
Cpp/Interpreter/Modder.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Interpreter/Modder.cpp.o
.PHONY : Cpp/Interpreter/Modder.cpp.o

Cpp/Interpreter/Modder.i: Cpp/Interpreter/Modder.cpp.i

.PHONY : Cpp/Interpreter/Modder.i

# target to preprocess a source file
Cpp/Interpreter/Modder.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Interpreter/Modder.cpp.i
.PHONY : Cpp/Interpreter/Modder.cpp.i

Cpp/Interpreter/Modder.s: Cpp/Interpreter/Modder.cpp.s

.PHONY : Cpp/Interpreter/Modder.s

# target to generate assembly for a file
Cpp/Interpreter/Modder.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Interpreter/Modder.cpp.s
.PHONY : Cpp/Interpreter/Modder.cpp.s

Cpp/Lexer/Lexer.o: Cpp/Lexer/Lexer.cpp.o

.PHONY : Cpp/Lexer/Lexer.o

# target to build an object file
Cpp/Lexer/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Lexer/Lexer.cpp.o
.PHONY : Cpp/Lexer/Lexer.cpp.o

Cpp/Lexer/Lexer.i: Cpp/Lexer/Lexer.cpp.i

.PHONY : Cpp/Lexer/Lexer.i

# target to preprocess a source file
Cpp/Lexer/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Lexer/Lexer.cpp.i
.PHONY : Cpp/Lexer/Lexer.cpp.i

Cpp/Lexer/Lexer.s: Cpp/Lexer/Lexer.cpp.s

.PHONY : Cpp/Lexer/Lexer.s

# target to generate assembly for a file
Cpp/Lexer/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Lexer/Lexer.cpp.s
.PHONY : Cpp/Lexer/Lexer.cpp.s

Cpp/Linux/Linux.o: Cpp/Linux/Linux.cpp.o

.PHONY : Cpp/Linux/Linux.o

# target to build an object file
Cpp/Linux/Linux.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Linux/Linux.cpp.o
.PHONY : Cpp/Linux/Linux.cpp.o

Cpp/Linux/Linux.i: Cpp/Linux/Linux.cpp.i

.PHONY : Cpp/Linux/Linux.i

# target to preprocess a source file
Cpp/Linux/Linux.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Linux/Linux.cpp.i
.PHONY : Cpp/Linux/Linux.cpp.i

Cpp/Linux/Linux.s: Cpp/Linux/Linux.cpp.s

.PHONY : Cpp/Linux/Linux.s

# target to generate assembly for a file
Cpp/Linux/Linux.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Linux/Linux.cpp.s
.PHONY : Cpp/Linux/Linux.cpp.s

Cpp/OpC/IR.o: Cpp/OpC/IR.cpp.o

.PHONY : Cpp/OpC/IR.o

# target to build an object file
Cpp/OpC/IR.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/OpC/IR.cpp.o
.PHONY : Cpp/OpC/IR.cpp.o

Cpp/OpC/IR.i: Cpp/OpC/IR.cpp.i

.PHONY : Cpp/OpC/IR.i

# target to preprocess a source file
Cpp/OpC/IR.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/OpC/IR.cpp.i
.PHONY : Cpp/OpC/IR.cpp.i

Cpp/OpC/IR.s: Cpp/OpC/IR.cpp.s

.PHONY : Cpp/OpC/IR.s

# target to generate assembly for a file
Cpp/OpC/IR.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/OpC/IR.cpp.s
.PHONY : Cpp/OpC/IR.cpp.s

Cpp/Parser/Parser.o: Cpp/Parser/Parser.cpp.o

.PHONY : Cpp/Parser/Parser.o

# target to build an object file
Cpp/Parser/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Parser/Parser.cpp.o
.PHONY : Cpp/Parser/Parser.cpp.o

Cpp/Parser/Parser.i: Cpp/Parser/Parser.cpp.i

.PHONY : Cpp/Parser/Parser.i

# target to preprocess a source file
Cpp/Parser/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Parser/Parser.cpp.i
.PHONY : Cpp/Parser/Parser.cpp.i

Cpp/Parser/Parser.s: Cpp/Parser/Parser.cpp.s

.PHONY : Cpp/Parser/Parser.s

# target to generate assembly for a file
Cpp/Parser/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Parser/Parser.cpp.s
.PHONY : Cpp/Parser/Parser.cpp.s

Cpp/Selector/Selector.o: Cpp/Selector/Selector.cpp.o

.PHONY : Cpp/Selector/Selector.o

# target to build an object file
Cpp/Selector/Selector.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Selector/Selector.cpp.o
.PHONY : Cpp/Selector/Selector.cpp.o

Cpp/Selector/Selector.i: Cpp/Selector/Selector.cpp.i

.PHONY : Cpp/Selector/Selector.i

# target to preprocess a source file
Cpp/Selector/Selector.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Selector/Selector.cpp.i
.PHONY : Cpp/Selector/Selector.cpp.i

Cpp/Selector/Selector.s: Cpp/Selector/Selector.cpp.s

.PHONY : Cpp/Selector/Selector.s

# target to generate assembly for a file
Cpp/Selector/Selector.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Selector/Selector.cpp.s
.PHONY : Cpp/Selector/Selector.cpp.s

Cpp/UI/Producer.o: Cpp/UI/Producer.cpp.o

.PHONY : Cpp/UI/Producer.o

# target to build an object file
Cpp/UI/Producer.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/UI/Producer.cpp.o
.PHONY : Cpp/UI/Producer.cpp.o

Cpp/UI/Producer.i: Cpp/UI/Producer.cpp.i

.PHONY : Cpp/UI/Producer.i

# target to preprocess a source file
Cpp/UI/Producer.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/UI/Producer.cpp.i
.PHONY : Cpp/UI/Producer.cpp.i

Cpp/UI/Producer.s: Cpp/UI/Producer.cpp.s

.PHONY : Cpp/UI/Producer.s

# target to generate assembly for a file
Cpp/UI/Producer.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/UI/Producer.cpp.s
.PHONY : Cpp/UI/Producer.cpp.s

Cpp/UI/Usr.o: Cpp/UI/Usr.cpp.o

.PHONY : Cpp/UI/Usr.o

# target to build an object file
Cpp/UI/Usr.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/UI/Usr.cpp.o
.PHONY : Cpp/UI/Usr.cpp.o

Cpp/UI/Usr.i: Cpp/UI/Usr.cpp.i

.PHONY : Cpp/UI/Usr.i

# target to preprocess a source file
Cpp/UI/Usr.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/UI/Usr.cpp.i
.PHONY : Cpp/UI/Usr.cpp.i

Cpp/UI/Usr.s: Cpp/UI/Usr.cpp.s

.PHONY : Cpp/UI/Usr.s

# target to generate assembly for a file
Cpp/UI/Usr.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/UI/Usr.cpp.s
.PHONY : Cpp/UI/Usr.cpp.s

Cpp/Windows/Windows.o: Cpp/Windows/Windows.cpp.o

.PHONY : Cpp/Windows/Windows.o

# target to build an object file
Cpp/Windows/Windows.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Windows/Windows.cpp.o
.PHONY : Cpp/Windows/Windows.cpp.o

Cpp/Windows/Windows.i: Cpp/Windows/Windows.cpp.i

.PHONY : Cpp/Windows/Windows.i

# target to preprocess a source file
Cpp/Windows/Windows.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Windows/Windows.cpp.i
.PHONY : Cpp/Windows/Windows.cpp.i

Cpp/Windows/Windows.s: Cpp/Windows/Windows.cpp.s

.PHONY : Cpp/Windows/Windows.s

# target to generate assembly for a file
Cpp/Windows/Windows.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/Windows/Windows.cpp.s
.PHONY : Cpp/Windows/Windows.cpp.s

Cpp/main.o: Cpp/main.cpp.o

.PHONY : Cpp/main.o

# target to build an object file
Cpp/main.cpp.o:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/main.cpp.o
.PHONY : Cpp/main.cpp.o

Cpp/main.i: Cpp/main.cpp.i

.PHONY : Cpp/main.i

# target to preprocess a source file
Cpp/main.cpp.i:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/main.cpp.i
.PHONY : Cpp/main.cpp.i

Cpp/main.s: Cpp/main.cpp.s

.PHONY : Cpp/main.s

# target to generate assembly for a file
Cpp/main.cpp.s:
	$(MAKE) -f CMakeFiles/Evie.dir/build.make CMakeFiles/Evie.dir/Cpp/main.cpp.s
.PHONY : Cpp/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Evie"
	@echo "... edit_cache"
	@echo "... Cpp/Architecture/ARM/ARM.o"
	@echo "... Cpp/Architecture/ARM/ARM.i"
	@echo "... Cpp/Architecture/ARM/ARM.s"
	@echo "... Cpp/Architecture/x86/x86.o"
	@echo "... Cpp/Architecture/x86/x86.i"
	@echo "... Cpp/Architecture/x86/x86.s"
	@echo "... Cpp/Back/Back.o"
	@echo "... Cpp/Back/Back.i"
	@echo "... Cpp/Back/Back.s"
	@echo "... Cpp/Back/Definer.o"
	@echo "... Cpp/Back/Definer.i"
	@echo "... Cpp/Back/Definer.s"
	@echo "... Cpp/Back/Generator.o"
	@echo "... Cpp/Back/Generator.i"
	@echo "... Cpp/Back/Generator.s"
	@echo "... Cpp/Back/Token.o"
	@echo "... Cpp/Back/Token.i"
	@echo "... Cpp/Back/Token.s"
	@echo "... Cpp/Emulator/Emulator.o"
	@echo "... Cpp/Emulator/Emulator.i"
	@echo "... Cpp/Emulator/Emulator.s"
	@echo "... Cpp/Interpreter/Interpreter.o"
	@echo "... Cpp/Interpreter/Interpreter.i"
	@echo "... Cpp/Interpreter/Interpreter.s"
	@echo "... Cpp/Interpreter/Modder.o"
	@echo "... Cpp/Interpreter/Modder.i"
	@echo "... Cpp/Interpreter/Modder.s"
	@echo "... Cpp/Lexer/Lexer.o"
	@echo "... Cpp/Lexer/Lexer.i"
	@echo "... Cpp/Lexer/Lexer.s"
	@echo "... Cpp/Linux/Linux.o"
	@echo "... Cpp/Linux/Linux.i"
	@echo "... Cpp/Linux/Linux.s"
	@echo "... Cpp/OpC/IR.o"
	@echo "... Cpp/OpC/IR.i"
	@echo "... Cpp/OpC/IR.s"
	@echo "... Cpp/Parser/Parser.o"
	@echo "... Cpp/Parser/Parser.i"
	@echo "... Cpp/Parser/Parser.s"
	@echo "... Cpp/Selector/Selector.o"
	@echo "... Cpp/Selector/Selector.i"
	@echo "... Cpp/Selector/Selector.s"
	@echo "... Cpp/UI/Producer.o"
	@echo "... Cpp/UI/Producer.i"
	@echo "... Cpp/UI/Producer.s"
	@echo "... Cpp/UI/Usr.o"
	@echo "... Cpp/UI/Usr.i"
	@echo "... Cpp/UI/Usr.s"
	@echo "... Cpp/Windows/Windows.o"
	@echo "... Cpp/Windows/Windows.i"
	@echo "... Cpp/Windows/Windows.s"
	@echo "... Cpp/main.o"
	@echo "... Cpp/main.i"
	@echo "... Cpp/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

