type import()()

import func _glClear@4()()
import func _glClearColor@16()()
import func _glVertex2f@8()()
import func _glBegin@4()()
import func _glEnd@0()()
import func _glFlush@0()()
import func _glColor3f@12()()
import func _glfwInit()()
import func _glfwTerminate()()
import func _glfwCreateWindow()()
import func _glfwWindowShouldClose()()
import func _glfwPollEvents()()
import func _glfwMakeContextCurrent()()
import func _glfwSwapBuffers()()